version: 2

linters:
  disable-all: true
  enable:
    - dupl
    - govet
    - ineffassign
    - nakedret
    - revive
    - unused
    - staticcheck

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  dupl:
    threshold: 400

formatters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/Masterminds/vcs
