on: 
  pull_request:
  push:
    branches:
    - master

name: Linux Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x, 1.26.x]
        platform:
        - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Lint
      if: matrix.go-version == '1.26.x'
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
      with:
        version: v2.11.4
    - name: Install dependencies
      run: sudo apt install subversion mercurial bzr
    - name: Test
      run: make test
